name: Push to ECR

on:

  push:

    branches:

      - master

jobs:

  push_to_ecr:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Configure AWS credentials

        uses: aws-actions/configure-aws-credentials@v1

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ AWS_SECRET_ACCESS_KEY }}

          aws-region: us-west-2

      - name: Login to Amazon ECR

        id: login-ecr

        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image

        run: |

          docker build -t facebooc .

          docker tag facebooc:latest public.ecr.aws/o2u8f2p6/jimin:latest

      - name: Push Docker image to ECR

        run: |

          docker push public.ecr.aws/o2u8f2p6/jimin:latest

      - name: Display ECR image URL

        run: |

          echo ${{ steps.login-ecr.outputs.registry }}
